version: '3'

services:
    db-mysql:
        container_name: news_mysql
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: owner
            MYSQL_ROOT_PASSWORD: mtmr-data  # テキトーなパスワード
            MYSQL_PASSWORD: mtmr-data       # テキトーなパスワード
            MYSQL_DATABASE: mtmr-bot
        volumes:
            # - ./db-data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./mysql/init/:/docker-entrypoint-initdb.d

    api:
        container_name: news_api-gin
        build: ./api-gin
        ports:
            - 8080:8080
        volumes:
            - ./api-gin:/go/src/bot-api
        stdin_open: true # ←を追加
        depends_on:
            - 'db-mysql'
        #command:
        #    sh ./wait-for-it.sh news_mysql owner mtmr-data go run main.go

    swagger-editor:
        container_name: news_swagger-editor
        image: swaggerapi/swagger-editor
        ports:
            - "8081:8080"

    swagger-ui:
        container_name: news_swagger-ui
        image: swaggerapi/swagger-ui
        ports:
            - "8082:8080"
        volumes:
            - ./swagger/openapi.yaml:/openapi.yaml
        environment:
            SWAGGER_JSON: /openapi.yaml
