openapi: 3.0.0
info:
  description: This is a News API server.
  version: 1.0.0
  title: Swagger News
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: trains
    description: Everything about trains
paths:
  "/trains/{Id}":
    get:
      tags:
        - trains
      summary: Find trains by id
      description: Returns a single pet
      operationId: getPetById
      parameters:
        - name: Id
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrainJrGroups"
        "404":
          description: Pet not found
servers:
  - url: http://localhost:8080
components:
  schemas:
    TrainJrGroups:
      type: object
      required:
        - id
        - lineName
      properties:
        id:
          type: integer
          format: int64
        lineName:
          type: string
        lineNameHira:
          type: string
        lineNameKana:
          type: string
        lineGroup:
          type: string
